# Generated by Django 3.2.5 on 2021-08-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permutas', '0003_auto_20210811_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='preferenciaspermutas',
            name='info_centro',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
