# Generated by Django 3.2.5 on 2021-08-19 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('permutas', '0004_preferenciaspermutas_info_centro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permuta',
            name='profe_1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_1', to='permutas.preferenciaspermutas'),
        ),
        migrations.AlterField(
            model_name='permuta',
            name='profe_2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pro_2', to='permutas.preferenciaspermutas'),
        ),
    ]
