# Generated by Django 2.2 on 2019-07-16 18:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Centro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('nome', models.CharField(max_length=50)),
                ('coorlat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('coorlon', models.DecimalField(decimal_places=6, max_digits=9)),
                ('enderezo', models.CharField(max_length=100)),
                ('cp', models.IntegerField()),
                ('web', models.URLField()),
                ('telefono', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Concello',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('provincia', models.CharField(choices=[('AC', 'A Coruña'), ('AC', 'Lugo'), ('AC', 'Ourense'), ('AC', 'Pontevedra')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Ensinanza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('INF', 'Educación Infantil'), ('PRI', 'Educación Primaria'), ('ESO', 'Educación Secundaria Obrigatoria'), ('BAC', 'Bacharelato'), ('EBI', 'Educacións Básicas Iniciais'), ('ESA', 'Educación Secundaria para Adultos'), ('BACA', 'Bacharelato de Adultos'), ('ESP', 'Educación Especial'), ('FPB', 'Formación Profesional Básica'), ('FPM', 'Formación Profesional (Grado Medio)'), ('FPS', 'Formación Profesional (Grado Superior)'), ('MUS', 'Música'), ('ARDE', 'Arte e Deseño'), ('IDI', 'Idiomas'), ('DAN', 'Danza'), ('ARDR', 'Arte Dramático')], max_length=4)),
                ('nome', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Servizo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Xornada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('IN', 'Infantil'), ('PR', 'Primaria')], max_length=2)),
                ('tipo_xornada', models.CharField(choices=[('PA', 'Partida'), ('CO', 'Continua'), ('MI', 'Mixta')], max_length=2)),
                ('centro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='centros.Centro')),
            ],
        ),
        migrations.AddField(
            model_name='centro',
            name='concello',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='centros.Concello'),
        ),
        migrations.AddField(
            model_name='centro',
            name='ensinanzas',
            field=models.ManyToManyField(to='centros.Ensinanza'),
        ),
        migrations.AddField(
            model_name='centro',
            name='servizos',
            field=models.ManyToManyField(to='centros.Servizo'),
        ),
    ]
