# Generated by Django 2.2 on 2019-07-17 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='concello',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='centros.Concello'),
        ),
        migrations.AlterField(
            model_name='centro',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='centro',
            name='web',
            field=models.URLField(blank=True, null=True),
        ),
    ]
