# Generated by Django 2.2 on 2019-07-17 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0002_auto_20190717_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centro',
            name='codigo',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='concello',
            name='provincia',
            field=models.CharField(choices=[('AC', 'A Coruña'), ('LU', 'Lugo'), ('OU', 'Ourense'), ('PO', 'Pontevedra')], max_length=2),
        ),
    ]
