# Generated by Django 2.2 on 2021-02-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0004_auto_20190718_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xornada',
            name='centro',
        ),
        migrations.RemoveField(
            model_name='centro',
            name='servizos',
        ),
        migrations.DeleteModel(
            name='Servizo',
        ),
        migrations.DeleteModel(
            name='Xornada',
        ),
    ]
