# Generated by Django 3.2.5 on 2021-08-03 10:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0007_rename_listacentro_listacentros'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacentros',
            name='data',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
