# Generated by Django 3.2.5 on 2021-08-03 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centros', '0008_listacentros_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacentros',
            name='deletable',
            field=models.BooleanField(default=True),
        ),
    ]
