# Generated by Django 2.2 on 2019-06-13 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profe',
            name='especialidade',
        ),
        migrations.DeleteModel(
            name='Especialidade',
        ),
    ]
