# Generated by Django 3.2.5 on 2021-08-01 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profe', '0002_auto_20190613_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profe',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
